version: 2
jobs:
  "go-1.9":
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/diverse-inc/jp_prefecture
    steps:
      - checkout
      - run:
          name: Run tests
          command: gotestsum --format standard-verbose --junitfile ./unit-tests.xml -- -cover
      - store_test_results:
          path: ./
  "go-1.10":
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/diverse-inc/jp_prefecture
    steps:
      - checkout
      - run:
          name: Run tests
          command: gotestsum --format standard-verbose --junitfile ./unit-tests.xml -- -cover
      - store_test_results:
          path: ./
  "go-1.11":
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/diverse-inc/jp_prefecture
    steps:
      - checkout
      - run:
          name: Run tests
          command: gotestsum --format standard-verbose --junitfile ./unit-tests.xml -- -cover
      - store_test_results:
          path: ./
